# Generated by Django 3.2.7 on 2021-09-20 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='hospital_choice',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Dhaka Medical College Hospital'), (2, 'Delta Medical College')], null=True),
        ),
    ]
